/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MainListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheMainListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheMainListGenerated.onFilterBar().iCheckFilterField({ property: "Custno" });
            Then.onTheMainListGenerated.onFilterBar().iCheckFilterField({ property: "Manager" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheMainListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheMainListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheMainListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheMainListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheMainListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheMainListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"Logourl":{"header":"회사로고URL"},"Custno":{"header":"고객업체코드"},"Buildate":{"header":"구축일자"},"Manager":{"header":"운영 담당자"},"Persno":{"header":"고객 담당자"},"Custlevel":{"header":"고객등급"},"Builnote":{"header":"구축개요"},"Vpnnote":{"header":"접속개요"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheMainListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheMainListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheMainListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheMainObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});