/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MainObjectPageObjectPage journey");

        opaTest("Navigate to MainObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheMainListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheMainListGenerated.onTable().iCheckRows();
            When.onTheMainListGenerated.onTable().iPressRow(0);

            Then.onTheMainObjectPageGenerated.iSeeThisPage();
        });


        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheMainObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "headdatapoint" });
            Then.onTheMainObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "headdatapoint",
                field: "Persno",
                targetAnnotation: ""
            });
            Then.onTheMainObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "headdatapoint",
                field: "Custphone",
                targetAnnotation: ""
            });
            Then.onTheMainObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "headdatapoint",
                field: "Custemail",
                targetAnnotation: ""
            });
            Then.onTheMainObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "timestamp01" });
            Then.onTheMainObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "timestamp01",
                field: "CreatedBy",
                targetAnnotation: ""
            });
            Then.onTheMainObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "timestamp01",
                field: "CreatedAt",
                targetAnnotation: ""
            });
            Then.onTheMainObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "timestamp01",
                field: "LastChangedBy",
                targetAnnotation: ""
            });
            Then.onTheMainObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "timestamp01",
                field: "LastChangedAt",
                targetAnnotation: ""
            });
        });

        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheMainObjectPageGenerated.iCheckNumberOfSections(4);
        });

        opaTest("Check the GeneralSection section of the Object Page", function (_Given, When, Then) {
            When.onTheMainObjectPageGenerated.iGoToSection({ section: "GeneralSection" });
            Then.onTheMainObjectPageGenerated.iCheckSection({ section: "GeneralSection" });
            Then.onTheMainObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "Custno" });
            Then.onTheMainObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "Custname" });
            Then.onTheMainObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "Custlevel" });
            Then.onTheMainObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "Buildate" });
            Then.onTheMainObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "Manager" });
            Then.onTheMainObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "Builnote" });
            Then.onTheMainObjectPageGenerated.onForm({ section: "GeneralSection" }).iCheckField({ property: "Vpnnote" });
        });

        opaTest("Check the connectSection section of the Object Page", function (_Given, When, Then) {
            When.onTheMainObjectPageGenerated.iGoToSection({ section: "connectSection" });
            Then.onTheMainObjectPageGenerated.iCheckSection({ section: "connectSection" });
            Then.onTheMainObjectPageGenerated.onForm({ section: "connectSection" }).iCheckField({ property: "Sapver" });
            Then.onTheMainObjectPageGenerated.onForm({ section: "connectSection" }).iCheckField({ property: "Vpninfo" });
            Then.onTheMainObjectPageGenerated.onForm({ section: "connectSection" }).iCheckField({ property: "Sapinfo" });
            Then.onTheMainObjectPageGenerated.onForm({ section: "connectSection" }).iCheckField({ property: "Sapinfoq" });
            Then.onTheMainObjectPageGenerated.onForm({ section: "connectSection" }).iCheckField({ property: "Sapinfop" });
        });

        opaTest("Check the otherSection section of the Object Page", function (_Given, When, Then) {
            When.onTheMainObjectPageGenerated.iGoToSection({ section: "otherSection" });
            Then.onTheMainObjectPageGenerated.iCheckSection({ section: "otherSection" });
            Then.onTheMainObjectPageGenerated.onForm({ section: "otherSection" }).iCheckField({ property: "Repres" });
            Then.onTheMainObjectPageGenerated.onForm({ section: "otherSection" }).iCheckField({ property: "Homepage" });
            Then.onTheMainObjectPageGenerated.onForm({ section: "otherSection" }).iCheckField({ property: "Address" });
            Then.onTheMainObjectPageGenerated.onForm({ section: "otherSection" }).iCheckField({ property: "Content" });
        });

        opaTest("Check the _Manager section of the Object Page", function (_Given, When, Then) {
            When.onTheMainObjectPageGenerated.iGoToSection({ section: "_Manager" });
            Then.onTheMainObjectPageGenerated.iCheckSection({ section: "_Manager" });
            Then.onTheMainObjectPageGenerated.onTable({ property: "_Manager" }).iCheckColumns(undefined, {"Persno":{"header":"고객담당자"},"Posit":{"header":"직책"},"Unit":{"header":"부서"},"Email":{"header":"이메일"},"Phone":{"header":"전화번호"},"Zdefault":{"header":"기본담당자"},"Delflag":{"header":"삭제플래그"},"Remark":{"header":"비고"}});
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});